const { GoogleGenAI } = require("@google/genai");
require("dotenv").config();
const { z } = require('zod')
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")

// ✅ Initialize AI
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

// ✅ Helper: truncate large input
const truncate = (text, max = 2000) => {
  if (!text) return "";
  return text.length > max ? text.slice(0, max) : text;
};

// ✅ Main Function
async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

  const prompt = `
You are an AI interview assistant.

Return ONLY valid JSON.

STRICT RULES:
- technicalQuestions MUST be an array of OBJECTS with question, intention, answer
- behavioralQuestions MUST be an array of OBJECTS with question, intention, answer
- skillGaps MUST be an array of OBJECTS with skill and severity
- preparationPlan MUST be an array of OBJECTS with day, focus, tasks
- Do NOT return strings instead of objects
- Do NOT include explanation or markdown

FORMAT:

{
  "matchScore": 85,
  "technicalQuestions": [
    {
      "question": "What is Node.js?",
      "intention": "Check backend basics",
      "answer": "Explain event-driven architecture"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "Tell me about a challenge",
      "intention": "Evaluate problem solving",
      "answer": "Use STAR method"
    }
  ],
  "skillGaps": [
    {
      "skill": "System Design",
      "severity": "high"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focus": "Node.js",
      "tasks": ["Learn event loop"]
    }
  ],
  "title": "Backend Developer"
}

Candidate Data:
Resume: ${truncate(resume)}
Self Description: ${truncate(selfDescription)}
Job Description: ${truncate(jobDescription)}
`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-lite",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    // ✅ Extract text safely
    const rawText =
      response.text ||
      response.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!rawText) {
      console.log("No response from AI");
      return;
    }

    const parsed = JSON.parse(rawText);

    // ✅ Just log the output
    // console.log("Generated Interview Report:\n", parsed);

    return parsed;

  } catch (error) {
    console.error("Error generating report:", error.message);
  }
}

const generateResumePdf = async ({ resume, selfDescription, jobDescription }) => {
  const resumePdfSchema = z.object({
    html: z.string().describe("HTML content of the resume which is generated by the AI based on the resume, self description and job description provided by the user. This HTML will be used to generate a PDF resume.")
  })

  const prompt = `You are an AI resume builder. Generate an HTML resume based on the following information.

Candidate Data:
Resume: ${truncate(resume)}
Self Description: ${truncate(selfDescription)}
Job Description: ${truncate(jobDescription)}`

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-lite",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseJsonSchema: zodToJsonSchema(resumePdfSchema),
      },
    });

    const rawText =
      response.text ||
      response.candidates?.[0]?.content?.parts?.[0]?.text;

      // console.log(rawText);
      
    if (!rawText) {
      console.log("No response from AI");
      return;
    }

    const parsed = JSON.parse(rawText);
    console.log(parsed.resume);
    
    const pdfBuffer = await generatePdfFromHtml(parsed.resume);
    return pdfBuffer;

  } catch (error) {
    console.error("Error generating resume HTML:", error.message);
  }
}

const generatePdfFromHtml = async (htmlContent) => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4' });
  await browser.close();
  return pdfBuffer;
}

module.exports = { generateInterviewReport, generateResumePdf };